### ISSUE TITLE
[EPIC] ETQ commercial je veux qu'il y ait un jeu minimaliste gratuit pour qu'un prospect puisse tester sa config matérielle.

### ISSUE THREAD

**Issue by Aenorya** [natoine/tryGameAutonomoov#5]
- [ ] 1 - 4 joueurs
- [ ] Main droite / main gauche
- [ ] Chaque joueur déplace un viseur de couleur différente
- [ ] Chaque joueur doit amener son viseur aux extremités de l'écran (pour atteindre les premiers ballons à éclater) afin de réaliser une calibration
- [ ] Des ballons de couleurs différentes apparaissent
- [ ] Quand un joueur touche un ballon de sa couleur, il marque des points
- [ ] Quand il touche un ballon d'une autre couleur, il perd des points

**Comment by natoine** [comment]
Dans l'idéal faudrait faire un jeu inspiré du "duck hunt" de Wii et du jeu de ballons de baudruche de Hopale.
Le jeu de Hopale s'appelle Baudruche
http://www.fondation-hopale.org/Partenaires/Projet-Shiva
